project:
  type: website
  output-dir: docs

website:
  title: "SEMANTICS"
  navbar:
    left:
      - href: blog.qmd
        text: BLOG
      - href: about.qmd
        text: ABOUT

  repo-url: https://github.com/morrijos/semantic
  repo-actions: [source, edit, issue]

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



